name: Saludo usando variables y secretos
run-name: ¡Estoy aprendiendo a utilizar variables!
on:
    workflow_dispatch
env:
    DIA_DE_SEMANA: Lunes
jobs:
    saludo-variables:
        runs-on: ubuntu-latest
        env:
            SALUDO: Hola
        steps:
            - name: saludar
              run: echo "$SALUDO, ${{ vars.NOMBRE }}, hoy es ${{ ENV.DIA_DE_SEMANA }}."
    saludo-secretos:
      runs-on: ubuntu-latest
      env:
            SALUDO: Hola
      steps:
        - name: Saludo secreto
          run: echo "$SALUDO, ${{ vars.NOMBRE }}, tu contraseña es ${{ secrets.CONTRASENA }}."
